<header class="w3-container w3-teal">
<img src="images/utfsm.png" alt="" height="100px" align="left"/>
<img src="images/mat.png" alt="" height="100px" align="right"/>
</header>
<br/><br/><br/><br/><br/>
# MAT281
## Laboratorio Aplicaciones de la Matemática en la Ingeniería
### Python Numérico
#### Fecha: Miercoles 28 Octubre 2015

## INSTRUCCIONES
* Anoten su nombre y rol en la celda siguiente.
* Desarrollen los problemas de manera secuencial.
* Guarden constantemente con ***Ctr-S*** para evitar sorpresas.
* Reemplacen en las celdas de código donde diga #FIX_ME por el código correspondiente.
* Ejecuten cada celda de código utilizando ***Ctr-Enter***

In [34]:
#Configuracion para recargar módulos y librerías cada vez 
%reload_ext autoreload
%autoreload 2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
%matplotlib inline
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
from mat281_code.lab import *
from IPython.core.display import HTML

HTML(open("style/mat281.css", "r").read())

alumno_1 = ("Sebastian Flores", "2004001-7")
alumno_2 = ("Maria Jose Vargas", "2004007-8")

HTML(greetings(alumno_1, alumno_2))

## Contenido
1. Overview de Numpy y Scipy
2. Librería Numpy
  * Arreglos vs Matrices
  * Axis
  * Funciones basicas.
  * Operaciones Vectoriales
  * Input y Output
3. Tips

## Overview de Numpy y scipy

ORIGEN, LA HISTORIA.

Numpy: Matrices deben contener variables con el mismo tipo de datos: sólo enteros, sólo flotantes, sólo complejos, sólo booleanos o sólo strings. La uniformicidad de los datos es lo que permite acelerar los cálculos con implementaciones en C a bajo nivel.

## Librería Numpy
Siempre importaremos la librería numpy de la siguiente forma:

    import numpy as np
    
Todas las funciones y módulos de numpy quedan a nuestro alcance a 3 carácteres de distancia:

    np.array([1,4,9,16])
    np.linspace(0.,1.,100)
    
Evite a todo costo utilizar lo siguiente:

    from numpy import *

In [106]:
import numpy as np
print np.version.version # Si alguna vez tienen problemas, verifiquen su version de numpy

1.8.2


#### 2. Librería Numpy
## 2.1 Array vs Matrix

Por defecto, la gran mayoria de las funciones de numpy y de scipy asumen que se les pasará un objeto de tipo **array**. 

Veremos las diferencias entre los objetos array y matrix, pero recuerden utilizar array mientras sea posible.

* **np.matrix**: Se comporta exactamente como una matriz. 
Si A y B son 2 matrices

#### 2.1 Array vs Matrix
## Matrix

Una matrix de numpy se comporta exactamente como esperaríamos de una matriz:

### Pros:
* Multiplicación utiliza el signo * como es esperable.
* 

### Contras:
* Todas las matrices deben estar completamente alineadas para poder operar correctamente.
* Operaciones elementwise son mas dificiles de definir/acceder.
* Están exclusivamente definidas en 2D: Un vector fila o un vector columna siguen siendo 2D.

In [41]:
# Operaciones con np.matrix
A = np.matrix([[1,2],[3,4]])
B = np.matrix([[1, 1],[0,1]], dtype=float)
x = np.matrix([[1],[2]])
print "A =\n", A
print "B =\n", B
print "x =\n", x

print "A+B =\n", A+B
print "A*B =\n", A*B
print "A*x =\n", A*x
print "A*A = A^2 =\n", A**2
print "x.T*A =\n", x.T * A


A =
[[1 2]
 [3 4]]
B =
[[ 1.  1.]
 [ 0.  1.]]
x =
[[1]
 [2]]
A+B =
[[ 2.  3.]
 [ 3.  5.]]
A*B =
[[ 1.  3.]
 [ 3.  7.]]
A*x =
[[ 5]
 [11]]
A*A = A^2 =
[[ 7 10]
 [15 22]]
x.T*A =
[[ 7 10]]


#### 2.1 Array vs Matrix
## Array

Un array de numpy es simplemente un contenedor multidimensional.

### Pros:
* Es multidimensional: 1D, 2D, 3D, ...
* Resulta consistente: todas las operaciones son element-wise a menos que se utilice una función específica.

### Contras:
* Multiplicación maticial utiliza la función **dot()**

In [43]:
# Operaciones con np.matrix
A = np.array([[1,2],[3,4]])
B = np.array([[1, 1],[0,1]], dtype=float)
x = np.array([1,2]) # No hay necesidad de definir como fila o columna!
print "A =\n", A
print "B =\n", B
print "x =\n", x

print "A+B =\n", A+B
print "AoB = (multiplicacion elementwise) \n", A*B
print "A*B = (multiplicacion matricial, v1) \n", np.dot(A,B)
print "A*B = (multiplicacion matricial, v2) \n", A.dot(B)
print "A*A = A^2 = (potencia matricial)\n", np.power(A,2)
print "AoA = (potencia elementwise)\n", A**2
print "A*x =\n", np.dot(A,x)
print "x.T*A =\n", np.dot(x,A) # No es necesario transponer.

A =
[[1 2]
 [3 4]]
B =
[[ 1.  1.]
 [ 0.  1.]]
x =
[1 2]
A+B =
[[ 2.  3.]
 [ 3.  5.]]
AoB = (multiplicacion elementwise) 
[[ 1.  2.]
 [ 0.  4.]]
A*B = (multiplicacion matricial, v1) 
[[ 1.  3.]
 [ 3.  7.]]
A*B = (multiplicacion matricial, v2) 
[[ 1.  3.]
 [ 3.  7.]]
A*A = A^2 = (potencia matricial)
[[ 1  4]
 [ 9 16]]
AoA = (potencia elementwise)
[[ 1  4]
 [ 9 16]]
A*x =
[ 5 11]
x.T*A =
[ 7 10]


Los arrays se indexan de la forma "tradicional".

* Para un array ***unidimensional***: sólo tiene una indexacion. ¡No es ni fila ni columna!
* Para un array ***bidimensional***: primera componente son las filas, segunda componente son las columnas.
* Para un array ***tridimensional***: primera componente son las filas, segunda componente son las columnas, tercera componente la siguiente dimension.

<img src="images/anatomyarray.png" alt="" height="100px" align="left"/>

In [45]:
x = np.arange(9)   # "Vector" con valores del 0 al 8 
A = x.reshape(3,3) # Arreglo con valores del 0 al 8, en 3 filas y 3 columnas.
print "x = \n", x
print "A = \n", A
print "primera fila de A\n", A[0,:]
print "ultima columna de A\n", A[:,-1]

x = 
[0 1 2 3 4 5 6 7 8]
A = 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
primera fila de A
[0 1 2]
ultima columna de A
[2 5 8]


Cabe destacar que al tomar slices (subsecciones) de un arreglo obtenemos siempre un arreglo con menores dimensiones que el original.

#### 2. Librería Numpy
## 2.2 Funciones Básicas

Algunas funciones básicas que es conveniente conocer son las siguientes:
* **shape**: Entrega las dimensiones del arreglo. Siempre es una tupla.
* **len**: Entrega el número de elementos de la primera dimensión del arreglo.
* **ones**: Crea un arreglo con las dimensiones provistas e inicializado con valores 1. Por defecto array 1D.
* **zeros**: Crea un arreglo con las dimensiones provistas e inicializado con valores 1. Por defecto array 1D.
* **eye**: Crea un arreglo con las dimensiones provistas e inicializado con 1 en la diagonal. Por defecto array 2D.

In [70]:
#A = np.ones((2,8))
A = np.ones(3)
print "A = \n", A
print "A.shape =", A.shape
print "len(A) =", len(A)
B = np.zeros(3)
print "B = \n", B
print "B.shape =", B.shape
print "len(B) =", len(B)
C = np.eye(1,3)
print "C = \n", C
print "C.shape =", C.shape
print "len(C) =", len(C)

A = 
[ 1.  1.  1.]
A.shape = (3,)
len(A) = 3
B = 
[ 0.  0.  0.]
B.shape = (3,)
len(B) = 3
C = 
[[ 1.  0.  0.]]
C.shape = (1, 3)
len(C) = 1


In [71]:
#A = np.ones((2,8))
A = np.ones((3,3))
print "A = \n", A
print "A.shape =", A.shape
print "len(A) =", len(A)
B = np.zeros((3,3))
print "B = \n", B
print "B.shape =", B.shape
print "len(B) =", len(B)
C = np.eye(3) # Or  np.eye(3,3)
print "C = \n", C
print "C.shape =", C.shape
print "len(C) =", len(C)


A = 
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
A.shape = (3, 3)
len(A) = 3
B = 
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
B.shape = (3, 3)
len(B) = 3
C = 
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
C.shape = (3, 3)
len(C) = 3


In [73]:
#A = np.ones((2,8))
A = np.ones((2,5))
print "A = \n", A
print "A.shape =", A.shape
print "len(A) =", len(A)
B = np.zeros((2,5))
print "B = \n", B
print "B.shape =", B.shape
print "len(B) =", len(B)
C = np.eye(2,5)
print "C = \n", C
print "C.shape =", C.shape
print "len(C) =", len(C)

A = 
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
A.shape = (2, 5)
len(A) = 2
B = 
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
B.shape = (2, 5)
len(B) = 2
C = 
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]]
C.shape = (2, 5)
len(C) = 2


#### 2. Librería Numpy
## 2.2 Funciones Básicas

Algunas funciones básicas que es conveniente conocer son las siguientes:
* **reshape**: Convierte arreglo a nueva forma.
* **linspace**: Regresa un arreglo con valores linealmente espaciados.
* **diag(x)**: Si x es 1D, regresa array 2D con valores en diagonal. Si x es 2D, regresa valores de la diagonal.
* **sum**: Suma los valores del arreglo. Puede hacerse en general o a lo largo de un axis.
* **mean**: Calcula el promedio de los valores del arreglo. Puede hacerse en general o a lo largo de un axis.
* **std**: Calcula la desviación estándar de los valores del arreglo. Puede hacerse en general o a lo largo de un axis.

In [86]:
x = np.linspace(0., 1., 6)
A = x.reshape(3,2)
print "x = \n", x
print "A = \n", A

print "np.diag(x) = \n", np.diag(x)
print "np.diag(B) = \n", np.diag(A)

print ""
print "A.sum() = ", A.sum()
print "A.sum(axis=0) = ", A.sum(axis=0)
print "A.sum(axis=1) = ", A.sum(axis=1)

print ""
print "A.mean() = ", A.mean()
print "A.mean(axis=0) = ", A.mean(axis=0)
print "A.mean(axis=1) = ", A.mean(axis=1)

print ""
print "A.std() = ", A.std()
print "A.std(axis=0) = ", A.std(axis=0)
print "A.std(axis=1) = ", A.std(axis=1)

x = 
[ 0.   0.2  0.4  0.6  0.8  1. ]
A = 
[[ 0.   0.2]
 [ 0.4  0.6]
 [ 0.8  1. ]]
np.diag(x) = 
[[ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.2  0.   0.   0.   0. ]
 [ 0.   0.   0.4  0.   0.   0. ]
 [ 0.   0.   0.   0.6  0.   0. ]
 [ 0.   0.   0.   0.   0.8  0. ]
 [ 0.   0.   0.   0.   0.   1. ]]
np.diag(B) = 
[ 0.   0.6]

A.sum() =  3.0
A.sum(axis=0) =  [ 1.2  1.8]
A.sum(axis=1) =  [ 0.2  1.   1.8]

A.mean() =  0.5
A.mean(axis=0) =  [ 0.4  0.6]
A.mean(axis=1) =  [ 0.1  0.5  0.9]

A.std() =  0.341565025532
A.std(axis=0) =  [ 0.32659863  0.32659863]
A.std(axis=1) =  [ 0.1  0.1  0.1]


In [86]:
x = np.linspace(0., 1., 6)
A = x.reshape(3,2)
print "x = \n", x
print "A = \n", A

print "np.diag(x) = \n", np.diag(x)
print "np.diag(B) = \n", np.diag(A)

print ""
print "A.sum() = ", A.sum()
print "A.sum(axis=0) = ", A.sum(axis=0)
print "A.sum(axis=1) = ", A.sum(axis=1)

print ""
print "A.mean() = ", A.mean()
print "A.mean(axis=0) = ", A.mean(axis=0)
print "A.mean(axis=1) = ", A.mean(axis=1)

print ""
print "A.std() = ", A.std()
print "A.std(axis=0) = ", A.std(axis=0)
print "A.std(axis=1) = ", A.std(axis=1)

x = 
[ 0.   0.2  0.4  0.6  0.8  1. ]
A = 
[[ 0.   0.2]
 [ 0.4  0.6]
 [ 0.8  1. ]]
np.diag(x) = 
[[ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.2  0.   0.   0.   0. ]
 [ 0.   0.   0.4  0.   0.   0. ]
 [ 0.   0.   0.   0.6  0.   0. ]
 [ 0.   0.   0.   0.   0.8  0. ]
 [ 0.   0.   0.   0.   0.   1. ]]
np.diag(B) = 
[ 0.   0.6]

A.sum() =  3.0
A.sum(axis=0) =  [ 1.2  1.8]
A.sum(axis=1) =  [ 0.2  1.   1.8]

A.mean() =  0.5
A.mean(axis=0) =  [ 0.4  0.6]
A.mean(axis=1) =  [ 0.1  0.5  0.9]

A.std() =  0.341565025532
A.std(axis=0) =  [ 0.32659863  0.32659863]
A.std(axis=1) =  [ 0.1  0.1  0.1]


# Ejercicio 1

Complete el siguiente código:
* Se le provee una matriz A
* Calcule una matriz B como la multiplicación element-wise de A por si misma.
* Calcule una matriz C como la multiplicación matricial de A y B.
* Imprima la matriz C resultante.
* Calcula la suma, promedio y desviación estándar de los valores en la diagonal.

In [99]:
A = np.outer(np.arange(3),np.arange(3))
print A
B = A*A
print B
C = np.dot(A, B)
print C
suma_diag = np.diag(C).sum()
mean_diag = np.diag(C).mean()
std_diag = np.diag(C).std()
print suma_diag
print mean_diag
print std_diag

[[0 0 0]
 [0 1 2]
 [0 2 4]]
[[ 0  0  0]
 [ 0  1  4]
 [ 0  4 16]]
[[ 0  0  0]
 [ 0  9 36]
 [ 0 18 72]]
81
27.0
32.0312347561


In [101]:
# Verificación
suma_diag == 81

#81, 27.0, 32.0312347561

True

#### 2. Librería Numpy
## 2.5 Inputs y Outputs

Numpy permite leer datos en formato array con la función **loadtxt**. Existen variados argumentos opcionales, pero los mas importantes son:
* **skiprows**: permite saltarse lineas en la lectura.
* **dtype**: declarar que tipo de dato tendra el array resultante

In [6]:
# Ejemplo de lectura de datos
data = np.loadtxt("data/cherry.txt")
print data.shape
print data

(31, 3)
[[  8.3  70.   10.3]
 [  8.6  65.   10.3]
 [  8.8  63.   10.2]
 [ 10.5  72.   16.4]
 [ 10.7  81.   18.8]
 [ 10.8  83.   19.7]
 [ 11.   66.   15.6]
 [ 11.   75.   18.2]
 [ 11.1  80.   22.6]
 [ 11.2  75.   19.9]
 [ 11.3  79.   24.2]
 [ 11.4  76.   21. ]
 [ 11.4  76.   21.4]
 [ 11.7  69.   21.3]
 [ 12.   75.   19.1]
 [ 12.9  74.   22.2]
 [ 12.9  85.   33.8]
 [ 13.3  86.   27.4]
 [ 13.7  71.   25.7]
 [ 13.8  64.   24.9]
 [ 14.   78.   34.5]
 [ 14.2  80.   31.7]
 [ 14.5  74.   36.3]
 [ 16.   72.   38.3]
 [ 16.3  77.   42.6]
 [ 17.3  81.   55.4]
 [ 17.5  82.   55.7]
 [ 17.9  80.   58.3]
 [ 18.   80.   51.5]
 [ 18.   80.   51. ]
 [ 20.6  87.   77. ]]


In [11]:
# Ejemplo de lectura de datos, saltandose 11 lineas y truncando a enteros
data_int = np.loadtxt("data/cherry.txt", skiprows=11, dtype=int)
print data_int.shape
print data_int

(21, 3)
[[11 79 24]
 [11 76 21]
 [11 76 21]
 [11 69 21]
 [12 75 19]
 [12 74 22]
 [12 85 33]
 [13 86 27]
 [13 71 25]
 [13 64 24]
 [14 78 34]
 [14 80 31]
 [14 74 36]
 [16 72 38]
 [16 77 42]
 [17 81 55]
 [17 82 55]
 [17 80 58]
 [18 80 51]
 [18 80 51]
 [20 87 77]]


#### 2. Librería Numpy
## 2.5 Inputs y Outputs

Numpy permite guardar datos de manera sencilla con la función **savetxt**: siempre debemos dar el nombre del archivo y el array a guardar. 

Existen variados argumentos opcionales, pero los mas importantes son:
* **header**: Línea a escribir como encabezado de los datos

In [18]:
# Guardando el archivo con un header en español
encabezado = "Diametro Altura Volumen (Valores truncados a numeros enteros)"
np.savetxt("data/cherry_int.txt", data_int, header=encabezado)

Revisemos si el archivo quedó bien escrito:

In [19]:
%%bash 
cat data/cherry_int.txt

# Diametro Altura Volumen (Valores truncados a numeros enteros)
1.100000000000000000e+01 7.900000000000000000e+01 2.400000000000000000e+01
1.100000000000000000e+01 7.600000000000000000e+01 2.100000000000000000e+01
1.100000000000000000e+01 7.600000000000000000e+01 2.100000000000000000e+01
1.100000000000000000e+01 6.900000000000000000e+01 2.100000000000000000e+01
1.200000000000000000e+01 7.500000000000000000e+01 1.900000000000000000e+01
1.200000000000000000e+01 7.400000000000000000e+01 2.200000000000000000e+01
1.200000000000000000e+01 8.500000000000000000e+01 3.300000000000000000e+01
1.300000000000000000e+01 8.600000000000000000e+01 2.700000000000000000e+01
1.300000000000000000e+01 7.100000000000000000e+01 2.500000000000000000e+01
1.300000000000000000e+01 6.400000000000000000e+01 2.400000000000000000e+01
1.400000000000000000e+01 7.800000000000000000e+01 3.400000000000000000e+01
1.400000000000000000e+01 8.000000000000000000e+01 3.100000000000000000e+01
1.400000000000000000e+01 7.400000000

# Ejercicio 2

* Lea el archivo data/cherry.txt
* Escale la matriz para tener todas las unidades en metros o metros cubicos.
* Guarde la matriz en un nuevo archivo data/cherry_mks.txt, con un encabezado apropiado.

In [102]:
# Leer datos
#FIX_ME#

# Convertir a mks
#FIX_ME#

# Guardar en nuevo archivo
#FIX_ME#

## Tips
La práctica y la necesidad hace al maestro.

Algunos enlaces útiles:
* http://www.labri.fr/perso/nrougier/teaching/numpy.100/ : Lista con 100 recetas prácticas.s
* http://sebastianraschka.com/Articles/2014_matlab_vs_numpy.html : Desde el lado oscuro a numpy.
* http://pages.physics.cornell.edu/~myers/teaching/ComputationalMethods/python/arrays.html : Otros consejos.